//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVshows.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int idFav { get; set; }
        public int idUs { get; set; }
        public int idCat { get; set; }
        public int idSh { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Shows Shows { get; set; }
        public virtual Users Users { get; set; }
    }
}
