//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVshows.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stencil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stencil()
        {
            this.Television = new HashSet<Television>();
        }
    
        public int idSt { get; set; }
        public int idCh { get; set; }
        public Nullable<int> idCat { get; set; }
        public int idDayOfWeek { get; set; }
        public System.TimeSpan tStart { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Channels Channels { get; set; }
        public virtual DaysOfWeek DaysOfWeek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Television> Television { get; set; }
    }
}
