//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVshows.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Television
    {
        public int idTv { get; set; }
        public int idSh { get; set; }
        public int idSt { get; set; }
    
        public virtual Shows Shows { get; set; }
        public virtual Stencil Stencil { get; set; }
    }
}
