//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVshows.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Television
    {
        public int idTv { get; set; }
        public int idSh { get; set; }
        public int idSt { get; set; }
    
        public virtual Shows Shows { get; set; }
        public virtual Stencil Stencil { get; set; }
    }
}
