//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVshows.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TVshowsEntities : DbContext
    {
        public TVshowsEntities()
            : base("name=TVshowsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Channels> Channels { get; set; }
        public virtual DbSet<DaysOfWeek> DaysOfWeek { get; set; }
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Shows> Shows { get; set; }
        public virtual DbSet<Stencil> Stencil { get; set; }
        public virtual DbSet<Television> Television { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
